### ISSUE TITLE
powやめる

### ISSUE THREAD

**Issue by hachi868** [miniRT-pien42/miniRT#52]

**Comment by habvi** [comment]
参考 : https://jp.quora.com/C%E3%81%AB%E3%81%8A%E3%81%84%E3%81%A6-%E5%A4%89%E6%95%B0-x-%E3%82%92%E4%BA%8C%E4%B9%97%E3%81%99%E3%82%8B%E5%A0%B4%E5%90%88-pow-x-2-0-%E3%82%88%E3%82%8A-x-x-%E3%81%8C%E6%9C%9B%E3%81%BE%E3%81%97%E3%81%84%E3%81%AE
